.MODEL SMALL
.STACK 100H
.CODE

MAIN PROC 
    
    MOV AH,1    ;AH,1 USE FOR ANY INPUT SEGMENT 
    INT 21H     ; EXECUTE LINE NO.7
    MOV BL,AL   ;NOW THE INPUT VALUE IS IN AL REGISTOR AND WE ASSING AL REGISTOR VALUE INTO BL REGISTOR
    
    
    MOV AH,1    ;AH,1 USE FOR ANY INPUT SEGMENT 
    INT 21H     ; EXECUTE LINE NO.12
    MOV BH,AL   ;NOW THE INPUT VALUE IS IN AL REGISTOR AND WE ASSING AL REGISTOR VALUE INTO BL REGISTOR
    
    
    ;FOR OUTPUT THESE VALUE 
    MOV AH,2    ; AH,2 USE FOR DISPLAY
    MOV DL,BL   ;BL USE FOR SHOW DATA WHICH IS IN TO BL
    INT 21H
    
    MOV AH,2
    MOV DL,BH
    INT 21H
    
    MOV AH,4CH  ; FOR EXIT THE PROGRAM 
    INT 21H
    MAIN ENDP
END MAIN 
    